<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit807d97f8bdb7ef536fc1f650df7cd490
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'RM_PODCAST\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'RM_PODCAST\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit807d97f8bdb7ef536fc1f650df7cd490::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit807d97f8bdb7ef536fc1f650df7cd490::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit807d97f8bdb7ef536fc1f650df7cd490::$classMap;

        }, null, ClassLoader::class);
    }
}
